### ISSUE TITLE
Symphony 2.6: Cookie handling is broken

### ISSUE THREAD

**Issue by michael-e** [symphonists/html_panel#12]
Using Symphony 2.6, there are issues with the field's cookie handling:

1. The user is logged out after having seen a page with an HTML Panel.
2. The Cookie does not allow using "admin" type pages for an HTML panel. So probably the cookie is incorrect.

**Comment by michael-e** [comment]
The log-out issue is caused by [session_write_close](https://github.com/symphonists/html_panel/blob/master/fields/field.html_panel.php#L81)

**Comment by nitriques** [comment]
@michael-e can you find the historical reason of that call in a render method ?

**Comment by michael-e** [comment]
[Here is the commit](https://github.com/symphonists/html_panel/commit/2159ba5547223726197ca0ad1e557f8c34c0648d). Unfortunately one can't see why it was done this way.

**Comment by nitriques** [comment]
Ok thanks a lot, I'll see what can be done!

**Comment by michael-e** [comment]
Currently I can not replicate this issue, so I will close it for now.

**Comment by michael-e** [comment]
It happens again, but I will have to test more in order to discover the mechanism. I'll be back.

**Comment by nitriques** [comment]
I'm ready for you @michael-e

**Comment by michael-e** [comment]
As far as I have tested, the log-out issue is indeed caused by `session_write_close`, so I commented this line — I am not sure if this is the best way to deal with this! Setting the cookie seems to work at the moment, because I can call admin type pages.

**Comment by nitriques** [comment]
Since I've never used this extension I would be willing to accept a PR that fixes it! Much work has been made around this nasty call in the core I think it's safe to remove it. Since we do not know the reason why it's there, it's fair to assume that it was as hack.

**Comment by michael-e** [comment]
OK, I will send a PR in the coming days.

**Comment by nitriques** [comment]
Perfect thanks.

**Comment by michael-e** [comment]
OMG, Github has not merged the tags. I will **push** them.
