### ISSUE TITLE
Issue with empty URL expression

### ISSUE THREAD

**Issue by vlad-ghita** [symphonists/html_panel#2]
When no URL expression is inserted at field creation in section, the sections' entries are messed up. Image attached in Symphony forum.

**Comment by michael-e** [comment]
I am not sure if this is a bug. Without a URL expression you will load the homepage of your website, which will simply break the backend's styling (if CSS rules are not namespaced completely, which won't be the case, normally).

**Comment by nitriques** [comment]
@michael-e why is the field requesting anything when empty ?

**Comment by michael-e** [comment]
Because it prepends the root of the website in this case. Maybe one could change this, however.

**Comment by nitriques** [comment]
Ah! Well no need to change this then. Thanks.
